[package]
name = "raytracing-weekend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
pixels = "0.9.0"
assert_approx_eq = "1.1.0"
rand = "0.8.4" 
rayon = "1.5.1"