name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, feature/* ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --manifest-path "./raytrace/Cargo.toml"
    - name: Run tests
      run: cargo test --verbose --manifest-path "./raytrace/Cargo.toml"